<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Version>0.0.0.1</Version>
		<PackageProjectUrl>https://github.com/AlmerisBE/Marketeer</PackageProjectUrl>
		<PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
		<IsPackable>false</IsPackable>
		<TargetFramework>net10.0-windows</TargetFramework>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="UI\**\*.json" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="Core\CharacterManagement\Resources\de.json" />
	  <EmbeddedResource Include="Core\CharacterManagement\Resources\en.json" />
	  <EmbeddedResource Include="Core\CharacterManagement\Resources\fr.json" />
	  <EmbeddedResource Include="Core\CharacterManagement\Resources\ja.json" />
	  <EmbeddedResource Include="Core\CompetitionTracking\Resources\de.json" />
	  <EmbeddedResource Include="Core\CompetitionTracking\Resources\en.json" />
	  <EmbeddedResource Include="Core\CompetitionTracking\Resources\fr.json" />
	  <EmbeddedResource Include="Core\CompetitionTracking\Resources\ja.json" />
	  <EmbeddedResource Include="Core\Configuration\Resources\de.json" />
	  <EmbeddedResource Include="Core\Configuration\Resources\en.json" />
	  <EmbeddedResource Include="Core\Configuration\Resources\fr.json" />
	  <EmbeddedResource Include="Core\Configuration\Resources\ja.json" />
	  <EmbeddedResource Include="Core\CraftingProfit\Resources\de.json" />
	  <EmbeddedResource Include="Core\CraftingProfit\Resources\en.json" />
	  <EmbeddedResource Include="Core\CraftingProfit\Resources\fr.json" />
	  <EmbeddedResource Include="Core\CraftingProfit\Resources\ja.json" />
	  <EmbeddedResource Include="Core\Financials\Resources\de.json" />
	  <EmbeddedResource Include="Core\Financials\Resources\en.json" />
	  <EmbeddedResource Include="Core\Financials\Resources\fr.json" />
	  <EmbeddedResource Include="Core\Financials\Resources\ja.json" />
	  <EmbeddedResource Include="Core\MarketListings\Resources\de.json" />
	  <EmbeddedResource Include="Core\MarketListings\Resources\en.json" />
	  <EmbeddedResource Include="Core\MarketListings\Resources\fr.json" />
	  <EmbeddedResource Include="Core\MarketListings\Resources\ja.json" />
	  <EmbeddedResource Include="Core\MarketWatch\Resources\de.json" />
	  <EmbeddedResource Include="Core\MarketWatch\Resources\en.json" />
	  <EmbeddedResource Include="Core\MarketWatch\Resources\fr.json" />
	  <EmbeddedResource Include="Core\MarketWatch\Resources\ja.json" />
	  <EmbeddedResource Include="Core\RetainerAutomation\Resources\de.json" />
	  <EmbeddedResource Include="Core\RetainerAutomation\Resources\en.json" />
	  <EmbeddedResource Include="Core\RetainerAutomation\Resources\fr.json" />
	  <EmbeddedResource Include="Core\RetainerAutomation\Resources\ja.json" />
	  <EmbeddedResource Include="Core\SalesHistory\Resources\de.json" />
	  <EmbeddedResource Include="Core\SalesHistory\Resources\en.json" />
	  <EmbeddedResource Include="Core\SalesHistory\Resources\fr.json" />
	  <EmbeddedResource Include="Core\SalesHistory\Resources\ja.json" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Core\CharacterManagement\Resources\" />
	  <Folder Include="Core\Configuration\Resources\" />
	  <Folder Include="Core\CraftingProfit\Resources\" />
	  <Folder Include="Core\Financials\Resources\" />
	  <Folder Include="UI\Guidance\Resources\" />
	  <Folder Include="UI\InventoryBrowser\Resources\" />
	  <Folder Include="Core\MarketListings\Resources\" />
	  <Folder Include="Core\MarketWatch\Resources\" />
	  <Folder Include="Core\RetainerAutomation\Resources\" />
	  <Folder Include="Core\SalesHistory\Resources\" />
	</ItemGroup>
</Project>
