<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Version>0.0.0.1</Version>
		<PackageProjectUrl>https://github.com/AlmerisBE/Marketeer</PackageProjectUrl>
		<PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
		<IsPackable>false</IsPackable>
		<TargetFramework>net10.0-windows</TargetFramework>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="UI\**\*.json" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="UI\Universalis\Resources\de.json" />
	  <Content Include="UI\Universalis\Resources\en.json" />
	  <Content Include="UI\Universalis\Resources\fr.json" />
	  <Content Include="UI\Universalis\Resources\ja.json" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="UI\Universalis\Resources\" />
	  <Folder Include="UI\CharacterManagement\Resources\" />
	  <Folder Include="UI\CraftingProfit\Resources\" />
	  <Folder Include="UI\Financials\Resources\" />
	  <Folder Include="UI\RetainerOverlays\Resources\" />
	  <Folder Include="UI\InventoryBrowser\Resources\" />
	  <Folder Include="UI\MarketListings\Resources\" />
	  <Folder Include="UI\RetainerAutomation\Resources\" />
	  <Folder Include="UI\SalesHistory\Resources\" />
	  <Folder Include="UI\Themes\Resources\" />
	</ItemGroup>
</Project>
